### ISSUE TITLE
Error issue

### ISSUE THREAD

**Issue by 1250364116** [ataradov/usb-sniffer-lite#14]
hi, i am testing your code. it gives for each keystroke an error. can you help me?

![Capture](https://github.com/ataradov/usb-sniffer-lite/assets/111889251/bdfe3822-7349-49f7-ada6-1983270047fe)

**Comment by ataradov** [comment]
This looks like legitimately broken frames. The decoded data must be correct, since overall flow is not broken.

My only guess here is that device clock frequency is way off and the error accumulates on the long packets, but the short ones are received correctly.

I would try with a different target device to see if you get a different result.
